openapi: 3.0.0
info:
  version: '1.0'
  title: hh.ru REST API
  contact:
    name: Artem
    email: tempmail@mail.ru
servers:
  - url: 'https://www.api.hh.ru/'
    description: Prod Server
tags:
  - name: Лабораторная работа №3
    description: |
      # Задание
      - Создать новый проект с @redocly/openapi-cli
      - Описать API предметной области по варианту в формате OpenAPI 3.0
      - Разместить спецификацию в отдельном репозитории Github
      - Опубликовать спецификацию на Github Pages используя ветку gh-pages
security:
  - OAuth2: []
paths:
  /resumes/mine:
    $ref: ./paths/resumes/mine.yaml
  /resumes/{resume_id}:
    $ref: ./paths/resumes/@{resume_id}.yaml
  /vacancies:
    $ref: ./paths/vacancies/vacancies.yaml
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants access to admin operations