openapi: 3.0.0
info:
  version: '1.0'
  title: booking.com REST API
  contact:
    name: Artem
    email: tempmail@mail.ru
servers:
  - url: 'https://www.api.booking.com/'
tags:
  - name: Лабораторная работа №3
    description: |
      # Задание
      - Создать новый проект с @redocly/openapi-cli
      - Описать API предметной области по варианту в формате OpenAPI 3.0
      - Разместить спецификацию в отдельном репозитории Github
      - Опубликовать спецификацию на Github Pages используя ветку gh-pages
security:
  - BearerAuth: []
paths:
  /registration:
    $ref: ./paths/registration.yaml
  # /resumes/mine:
  #   $ref: ./paths/resumes/mine.yaml
  # /resumes/{resume_id}:
  #   $ref: ./paths/resumes/@{resume_id}.yaml
  # /vacancies:
  #   $ref: ./paths/vacancies.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer