openapi: 3.0.0
info:
  version: '1.0'
  title: booking.com REST API
  contact:
    name: Artem
    email: tempmail@mail.ru
servers:
  - url: 'https://www.api.booking.com/'
tags:
  - name: Лабораторная работа №3
    description: |
      # Задание
      - Создать новый проект с @redocly/openapi-cli
      - Описать API предметной области по варианту в формате OpenAPI 3.0
      - Разместить спецификацию в отдельном репозитории Github
      - Опубликовать спецификацию на Github Pages используя ветку gh-pages
security:
  - BearerAuth: []
paths:
  /registration:
    $ref: ./paths/registration.yaml
  /auth:
    $ref: ./paths/auth.yaml
  /add-object:
    $ref: ./paths/object/add.yaml
  /get-object:
    $ref: ./paths/object/get.yaml
  /update-object:
    $ref: ./paths/object/update.yaml
  /delete-object:
    $ref: ./paths/object/delete.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer